blank_issues_enabled: false
contact_links:
  - name: 📘 Aurum Engine Documentation
    url: https://github.com/AurumEngineOrg/AurumDocs
    about: Read the official documentation before creating an issue.
  - name: 💬 Discussions
    url: https://github.com/AurumEngineOrg/AurumEngine/discussions
    about: Ask general questions or discuss ideas here instead of opening an issue.
