name: "📘 Documentation Issue"
description: "Report missing, outdated, or unclear documentation."
title: "[Docs] <Short Summary>"
labels:
  - "Type - Documentation"
  - "Priority - Low"

body:
  - type: dropdown
    id: doc_area
    attributes:
      label: "Documentation Section"
      options:
        - Getting Started
        - API Reference
        - Engine Editor
        - Scripting Guide
        - Build Instructions
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: "Describe the Issue"
      placeholder: "Explain what’s missing or wrong in the documentation."
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: "Suggested Fix or Addition"
      placeholder: "If possible, suggest corrected or improved text."
