name: "⚙️ Technical Task / Improvement"
description: "Refactor, optimize, or perform a technical improvement task."
title: "[Task] <Short Description>"
labels:
  - "Type - Task"
  - "Priority - Medium"

body:
  - type: dropdown
    id: area
    attributes:
      label: "Related System"
      options:
        - Area - Core
        - Area - Rendering
        - Area - Physics
        - Area - Audio
        - Area - Input
        - Area - Editor
        - Area - Networking
    validations:
      required: true

  - type: textarea
    id: task
    attributes:
      label: "Task Description"
      placeholder: "Describe the technical change or optimization."
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "Reason / Context"
      description: "Why is this task being done?"
      placeholder: "Example: Cleanup of old input manager before v0.7 release."
