name: 🐞 Auto Add Bug Issues to Projects

on:
  issues:
    types: [opened, labeled]

jobs:
  add-bug-issues:
    runs-on: ubuntu-latest

    # This conditional makes sure it only runs for Bug issues
    if: contains(join(fromJson(toJson(github.event.issue.labels)).*.name, ','), 'Type - Bug')

    steps:
      - name: Add issue to Bug Tracker project
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/AurumEngineOrg/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add issue to Core Development project
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/AurumEngineOrg/projects/2
          github-token: ${{ secrets.GITHUB_TOKEN }}
